import { Category, Product, Establishment } from '@/types';

// NOTA: mockAdmins foi removido por segurança
// Agora a autenticação de admin usa Supabase Auth + tabela user_roles

export const mockEstablishment: Establishment = {
  id: '1',
  name: 'Lanchonete do João',
  cpfCnpj: '12.345.678/0001-99',
  whatsapp: '11999999999',
  email: 'joao@lanchonete.com',
  pixKey: 'joao@lanchonete.com',
  trialStartDate: new Date(),
  trialEndDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
  planStatus: 'trial',
  createdAt: new Date(),
};

// Lista de estabelecimentos para o painel admin
export const mockEstablishments: Establishment[] = [
  mockEstablishment,
  {
    id: '2',
    name: 'Pizzaria Bella Napoli',
    cpfCnpj: '23.456.789/0001-88',
    whatsapp: '11988888888',
    email: 'contato@bellanapoli.com',
    pixKey: 'pix@bellanapoli.com',
    trialStartDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    trialEndDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    planStatus: 'expired',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    id: '3',
    name: 'Sushi Express',
    cpfCnpj: '34.567.890/0001-77',
    whatsapp: '11977777777',
    email: 'pedidos@sushiexpress.com',
    pixKey: 'sushi@pix.com',
    trialStartDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    trialEndDate: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000),
    planStatus: 'active',
    planExpiresAt: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
  },
  {
    id: '4',
    name: 'Açaí da Praia',
    cpfCnpj: '45.678.901/0001-66',
    whatsapp: '21966666666',
    email: 'acai@praia.com',
    pixKey: 'acai@pix.com',
    trialStartDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    trialEndDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    planStatus: 'trial',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: '5',
    name: 'Pet Shop Amigo Fiel',
    cpfCnpj: '56.789.012/0001-55',
    whatsapp: '11955555555',
    email: 'contato@amigofiel.com',
    pixKey: 'pet@pix.com',
    trialStartDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    trialEndDate: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000),
    planStatus: 'active',
    planExpiresAt: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
  },
  {
    id: '6',
    name: 'Farmácia Popular',
    cpfCnpj: '67.890.123/0001-44',
    whatsapp: '11944444444',
    email: 'farmacia@popular.com',
    trialStartDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    trialEndDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    planStatus: 'trial',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
];

export const mockCategories: Category[] = [
  { id: '1', establishmentId: '1', name: 'Lanches', order: 1 },
  { id: '2', establishmentId: '1', name: 'Bebidas', order: 2 },
  { id: '3', establishmentId: '1', name: 'Porções', order: 3 },
  { id: '4', establishmentId: '1', name: 'Sobremesas', order: 4 },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    categoryId: '1',
    establishmentId: '1',
    name: 'X-Burguer',
    description: 'Pão, hambúrguer artesanal 180g, queijo, alface, tomate e molho especial',
    price: 22.90,
    available: true,
    additions: [
      { id: 'a1', name: 'Bacon', price: 5.00 },
      { id: 'a2', name: 'Ovo', price: 3.00 },
      { id: 'a3', name: 'Queijo extra', price: 4.00 },
    ],
  },
  {
    id: '2',
    categoryId: '1',
    establishmentId: '1',
    name: 'X-Salada',
    description: 'Pão, hambúrguer 150g, queijo, alface, tomate, cebola e maionese',
    price: 18.90,
    available: true,
    additions: [
      { id: 'a1', name: 'Bacon', price: 5.00 },
      { id: 'a2', name: 'Ovo', price: 3.00 },
    ],
  },
  {
    id: '3',
    categoryId: '1',
    establishmentId: '1',
    name: 'X-Bacon',
    description: 'Pão, hambúrguer 180g, queijo, bacon crocante e molho barbecue',
    price: 26.90,
    available: true,
    additions: [
      { id: 'a3', name: 'Queijo extra', price: 4.00 },
      { id: 'a4', name: 'Cebola caramelizada', price: 4.50 },
    ],
  },
  {
    id: '4',
    categoryId: '2',
    establishmentId: '1',
    name: 'Refrigerante Lata',
    description: 'Coca-Cola, Guaraná ou Fanta (350ml)',
    price: 6.00,
    available: true,
    additions: [],
  },
  {
    id: '5',
    categoryId: '2',
    establishmentId: '1',
    name: 'Suco Natural',
    description: 'Laranja, limão ou maracujá (400ml)',
    price: 9.00,
    available: true,
    additions: [
      { id: 'a5', name: 'Açúcar extra', price: 0 },
    ],
  },
  {
    id: '6',
    categoryId: '3',
    establishmentId: '1',
    name: 'Batata Frita',
    description: 'Porção de batata frita crocante (300g)',
    price: 18.00,
    available: true,
    additions: [
      { id: 'a6', name: 'Cheddar', price: 5.00 },
      { id: 'a7', name: 'Bacon', price: 5.00 },
    ],
  },
  {
    id: '7',
    categoryId: '4',
    establishmentId: '1',
    name: 'Brownie com Sorvete',
    description: 'Brownie de chocolate com bola de sorvete de creme',
    price: 16.00,
    available: true,
    additions: [
      { id: 'a8', name: 'Calda de chocolate', price: 3.00 },
    ],
  },
];
